# This creates the following:
# - Container evolution-sim-nginx-1
# - Container evolution-sim-redis-1
# - Network evolution-sim_default

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html

  redis:
    image: redis
    ports:
      - 6379:6379 # This is default. But for reference purposes.
